# Generated by Django 4.2 on 2023-05-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('timeSlot', models.IntegerField()),
                ('timeMin', models.IntegerField()),
                ('manIn', models.BooleanField(default=False)),
                ('womanIn', models.BooleanField(default=False)),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timebox_set', to='blind.person')),
            ],
        ),
    ]
