# Generated by Django 4.2 on 2023-05-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0003_timebox_woman_alter_timebox_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
